services:
  backend:
    build: ./flask
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://cache:6379
      - PORT=5000
    depends_on:
      - cache
  cache:
    image: redis:alpine
