services:
  - type: web
    name: imc-app
    env: docker
    dockerContext: ./flask
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: imc-cache
          property: connectionString

  - type: redis
    name: imc-cache
    plan: free
    ipAllowList: []
